version: eel_application_version_1_MySQL

config:
  application:
    port: "9000"
  production:
    database_connection_options:
      db: "MySQL"
      host: "127.0.0.1"
      port: "3306"
      user: "root"
      pass: "Brerafra5618"
      name: "database_test"
      connect_timeout: 5,